### ISSUE TITLE
IOS 12.2 orientation bug

### ISSUE THREAD

**Issue by ponyspy** [micku7zu/vanilla-tilt.js#50]
In ios 12.2 apple implement new security policy and block by default motion and orientation events. But tilt not working even turn on this events in safari settings.

Safari show this message in debug tools:

Blocked attempt to add a device motion or orientation listener because the browsing context is not secure.

**Comment by micku7zu** [comment]
Sorry, but I don't think the problem is in the library. This is a specific problem related to your hosting solution and how you serve the content on that particular website.

> A context will be considered secure when it's delivered securely (or locally), and when it cannot be used to provide access to secure APIs to a context that is not secure. In practice this means that for a page to have a secure context, it and all the pages along its parent and opener chain must have been delivered securely.

I don't have any IOS device to test this. If you still think that this problem is related to the library, please reopen the issue with more details.
