### ISSUE TITLE
adding data-tilt attribute via js doesn't seem to work

### ISSUE THREAD

**Issue by sztan** [micku7zu/vanilla-tilt.js#78]
I tried to add like this : 

```
$(this).attr( 'data-tilt', '');
 $(this).attr( 'data-tilt-scale', '1.1');
```

(as per "Scale on hover" example on https://micku7zu.github.io/vanilla-tilt.js/)
The wished attributes then appear in the DOM on my element. But tilt effect won't trigger. 
(`<span class="skills badge text-dark bg-info bg-light masterbadge" data-tilt="" data-tilt-scale="1.1">PhP</span>`)
I've loaded the scripts as follows (in this order) :

```
<script src="index.js"></script> <!-- adds attributes as shown above--> 
<script type="text/javascript" src="vanilla-tilt.js"></script>
<script src="my_tilt.js"></script> <!-- inits effect (see below) -->
```

---

```
// my_tilt.js
$(function () {
    VanillaTilt.init(document.querySelectorAll(".job_header .enterprise"), {
        max  : 25,
        speed: 400
    });
});
```

If I directly write the attributes in the HTML page it's okay....

Sorry not sure if this is an issue but it looks like. (Chrome Version 89.0.4389.90 (Build officiel) (64 bits))

**Comment by micku7zu** [comment]
It doesn't matter if the attribute is added from HTML or from Javascript. It works from both, but you need to check your code for the order of execution. If the attributes are added after the VanillaTilt init it won't work, because the library was already initialized with the values that were present at that time.

Changing the data-tilt-scale attribute on the HTML element after the init it won't have any effect, you have to change it before initializing.
